"""New revision

Revision ID: 4f1c0edcf636
Revises: 8eb7a2f9aa2f
Create Date: 2025-03-12 20:58:54.757902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1c0edcf636'
down_revision: Union[str, None] = '8eb7a2f9aa2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('google_event_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    op.drop_column('sessions', 'google_event_id')
    # ### end Alembic commands ###
